/**
 * @calledit/db — thin typed data façade over Supabase for the Called It
 * engine. Exposes createEngineDb (service-role writes, RLS bypass) plus the
 * hand-written row types that mirror migrations/0001_init.sql.
 */

export { createEngineDb, type EngineDb } from './engine-db.js';
export {
  botOnboardingDbFromClient,
  createBotOnboardingDb,
  type BotOnboardingDbClient,
} from './bot-onboarding-db.js';
export type {
  BotGroupReadyResult,
  BotOnboardingDb,
  BotOnboardingVersion,
} from './bot-onboarding-types.js';
export { DbError } from './errors.js';
export type {
  Chattiness,
  ClaimInsert,
  ClaimPatch,
  ClaimRow,
  ClaimStatus,
  EntityNames,
  FeedEventRow,
  FixturePlayerRow,
  FixtureRow,
  FixtureUpsert,
  GroupRow,
  LeaderboardEntry,
  LedgerEntry,
  LedgerKind,
  LedgerRow,
  MarketCurrency,
  MarketInsert,
  MarketQuotePatch,
  MarketRow,
  MembershipRow,
  PlayerLite,
  PlayerRow,
  PositionInsert,
  PositionRow,
  PositionState,
  PriceProvenance,
  ProofKind,
  ProofRow,
  ProofStatus,
  ProofUpsert,
  SettlementInsert,
  SettlementRow,
  StreamCursorRow,
  UserRow,
} from './types.js';
export {
  assertSafeInteger,
  createWagerDb,
  multMilli,
  stakePayoutLamports,
  WAGER_MULT_SCALE,
  wagerDbFromClient,
  type WagerDb,
  type WagerDbClient,
  type WagerFilterBuilder,
  type WagerTableBuilder,
} from './wager-db.js';
export type {
  WagerDepositInsert,
  WagerDepositAttributionReason,
  WagerDepositAttributionState,
  WagerDepositCreditResult,
  WagerDepositRow,
  WagerGroupRow,
  WagerLedgerEntry,
  WagerLedgerKind,
  WagerLedgerRow,
  CreatePendingStakeIntentResult,
  MutatePendingStakeIntentResult,
  PendingStakeIntentErrorCode,
  PendingStakeIntentInput,
  PendingStakeIntentRow,
  PendingStakeIntentState,
  ResolvePendingStakeIntentResult,
  WagerSettlementAppliedRow,
  WagerStarterBudgetRow,
  WagerStarterGrantRow,
  WagerStakeErrorCode,
  WagerStakeInput,
  WagerStakeResult,
  WagerStatusRow,
  WagerSolvencySnapshot,
  WagerLegacyReconciliationReason,
  WagerLegacyReconciliationSummary,
  WagerWalletLinkRow,
  WagerWithdrawErrorCode,
  WagerWithdrawResult,
  WagerWithdrawalRow,
  WagerWithdrawalState,
  VerifiedWalletLinkErrorCode,
  VerifiedWalletLinkInput,
  VerifiedWalletLinkResult,
  WalletLinkChallengeInput,
} from './wager-types.js';
export {
  createTelegramDb,
  telegramDbFromClient,
  type TelegramDb,
  type TelegramDbClient,
} from './telegram-db.js';
export type {
  TelegramActionResult,
  TelegramDbCode,
  TelegramDeliverySnapshot,
  TelegramLeaseOwnershipItem,
  TelegramLeaseUpdateItem,
  TelegramOutboundState,
  TelegramPersistResult,
  TelegramPlanOutboundResult,
  TelegramPruneDeliveryResult,
  TelegramResolveOwnedMessageResult,
  TelegramRoutingDecision,
  TelegramStartOutboundResult,
  TelegramUpdateState,
  TelegramWorkerHeartbeatSnapshot,
  TelegramWorkerKind,
} from './telegram-types.js';
export {
  createSettlementProofJobsDb,
  settlementProofJobsDbFromClient,
  type SettlementProofJobsDbClient,
} from './settlement-proof-jobs.js';
export type {
  CompleteSettlementProofJobInput,
  DeadLetterSettlementProofJobInput,
  EnqueueSettlementProofJobInput,
  JobTransitionResult,
  LeaseSettlementProofJobsInput,
  ProofJobErrorCode,
  RecordProofStateInput,
  RecordProofStateResult,
  RecordTerminalSettlementInput,
  RecordTerminalSettlementResult,
  ReconcileTerminalJobReason,
  ReconcileTerminalJobResult,
  ReconcileTerminalJobsInput,
  RetrySettlementProofJobInput,
  SettlementJobErrorCode,
  SettlementPostedResult,
  SettlementProofBacklog,
  SettlementProofJobErrorCode,
  SettlementProofJobKind,
  SettlementProofJobRow,
  SettlementProofJobsDb,
  SettlementProofJobStatus,
  SettlementProofKind,
  SettlementProofOutcome,
  SettlementProofRpcCode,
  SettlementProofState,
  SettlementProofTier,
  TerminalSettlementGap,
} from './settlement-proof-job-types.js';
export {
  createProofSubmissionOutboxDb,
  proofSubmissionOutboxDbFromClient,
  type ProofSubmissionOutboxDbClient,
} from './proof-submission-outbox.js';
export type {
  GetProofSubmissionResult,
  PrepareProofSubmissionInput,
  ProofSubmissionIdentity,
  ProofSubmissionMutationResult,
  ProofSubmissionOutboxDb,
  ProofSubmissionOutboxRow,
  ProofSubmissionOutboxRpcCode,
  ProofSubmissionOutboxState,
} from './proof-submission-outbox-types.js';
