-- Called It -- privacy-safe public SOL data foundation.
--
-- This migration intentionally owns only the curated public surface. The engine
-- remains the private writer for memberships, markets, positions, and events.

-- ── Stable per-group aliases ────────────────────────────────────────────────

alter table memberships add column public_alias text;

create function membership_public_alias_candidate() returns text
language sql
volatile
set search_path = public
as $$
  select 'Player ' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8));
$$;

create function membership_assign_public_alias() returns trigger
language plpgsql
set search_path = public
as $$
begin
  if tg_op = 'UPDATE' and old.public_alias is not null then
    if new.public_alias is distinct from old.public_alias then
      raise exception 'membership public alias is immutable';
    end if;
    return new;
  end if;

  if new.public_alias is not null then
    raise exception 'membership public aliases are generated by the database';
  end if;

  -- All alias assignment for one group serializes here. The unique constraint
  -- below is the durable backstop; this loop retries a generated collision.
  perform pg_advisory_xact_lock(new.group_id);
  loop
    new.public_alias := membership_public_alias_candidate();
    exit when not exists (
      select 1
      from memberships
      where group_id = new.group_id
        and public_alias = new.public_alias
    );
  end loop;
  return new;
end;
$$;

create trigger memberships_assign_public_alias
before insert or update of public_alias on memberships
for each row execute function membership_assign_public_alias();

update memberships set public_alias = null where public_alias is null;

alter table memberships alter column public_alias set not null;
alter table memberships
  add constraint memberships_group_public_alias_key unique (group_id, public_alias);

-- ── Private, bounded onboarding telemetry ──────────────────────────────────

create table onboarding_events (
  idempotency_key       uuid primary key,
  session_id            uuid not null,
  event_name            text not null check (event_name in (
    'entry_viewed', 'add_group_clicked', 'bot_added', 'group_ready',
    'claim_detected', 'claim_confirmed', 'claim_priced', 'claim_failed',
    'offer_rendered', 'stake_tapped', 'starter_granted', 'wallet_required',
    'position_placed', 'stake_refused', 'wallet_setup_started', 'wallet_verified',
    'deposit_confirmed', 'pending_stake_confirmed', 'settlement_seen', 'receipt_opened'
  )),
  actor_pseudonym       text not null check (actor_pseudonym ~ '^[A-Za-z0-9_-]{43}$'),
  group_pseudonym       text not null check (group_pseudonym ~ '^[A-Za-z0-9_-]{43}$'),
  role_code             text not null check (role_code ~ '^[a-z][a-z0-9_]{0,47}$'),
  source_code           text not null check (source_code ~ '^[a-z][a-z0-9_]{0,47}$'),
  reason_code           text check (reason_code ~ '^[a-z][a-z0-9_]{0,47}$'),
  latency_ms            integer check (latency_ms between 0 and 86400000),
  amount_lamports       bigint check (amount_lamports >= 0),
  matched_lamports      bigint check (matched_lamports >= 0),
  proof_tier            text check (proof_tier in ('chain_proven', 'oracle_resolved')),
  proof_status          text check (proof_status in ('pending', 'verified', 'failed', 'unavailable')),
  created_at            timestamptz not null default now(),
  retention_expires_at  timestamptz not null
);

create index onboarding_events_retention_idx on onboarding_events (retention_expires_at);

create function onboarding_event_set_retention() returns trigger
language plpgsql
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    new.retention_expires_at := new.created_at + interval '30 days';
  elsif new.retention_expires_at is distinct from old.retention_expires_at then
    raise exception 'onboarding event retention is immutable';
  end if;
  return new;
end;
$$;

create trigger onboarding_events_set_retention
before insert or update of retention_expires_at on onboarding_events
for each row execute function onboarding_event_set_retention();

alter table onboarding_events enable row level security;

create function prune_onboarding_events(p_limit integer) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
begin
  if p_limit is null or p_limit < 1 or p_limit > 10000 then
    return jsonb_build_object('ok', false, 'code', 'invalid_input');
  end if;

  with candidates as (
    select idempotency_key
    from onboarding_events
    where retention_expires_at <= clock_timestamp()
    order by retention_expires_at, idempotency_key
    limit p_limit
  ), deleted as (
    delete from onboarding_events
    where idempotency_key in (select idempotency_key from candidates)
    returning 1
  )
  select count(*)::integer into v_count from deleted;

  return jsonb_build_object('ok', true, 'count', coalesce(v_count, 0));
end;
$$;

-- ── Curated public SOL views ───────────────────────────────────────────────

drop view public_receipts;
drop view public_leaderboard;

create view public_receipts as
with position_totals as (
  select
    p.market_id,
    coalesce(sum(p.stake) filter (where p.side = 'back'), 0)::bigint as back_pot_lamports,
    coalesce(sum(p.stake) filter (where p.side = 'doubt'), 0)::bigint as doubt_pot_lamports,
    coalesce(sum(p.stake) filter (where p.side = 'back' and p.state = 'active'), 0)::bigint as active_back_lamports,
    coalesce(sum(p.stake) filter (where p.side = 'doubt' and p.state = 'active'), 0)::bigint as active_doubt_lamports,
    count(*)::bigint as position_count
  from positions p
  group by p.market_id
), ledger_totals as (
  select
    l.market_id,
    coalesce(sum(l.lamports) filter (where l.kind = 'refund' and l.lamports > 0), 0)::bigint as refunded_amount_lamports,
    coalesce(sum(l.lamports) filter (where l.kind = 'payout' and l.lamports > 0), 0)::bigint as paid_amount_lamports
  from wager_ledger_entries l
  where l.market_id is not null
  group by l.market_id
)
select
  m.id as market_id,
  g.slug as group_slug,
  ms.public_alias as claimer_alias,
  m.spec,
  m.status,
  m.price_provenance,
  m.quote_probability,
  m.quote_multiplier,
  m.currency,
  coalesce(pt.back_pot_lamports, 0)::bigint::text as back_pot_lamports,
  coalesce(pt.doubt_pot_lamports, 0)::bigint::text as doubt_pot_lamports,
  coalesce(match_totals.matched_back_lamports + match_totals.matched_doubt_lamports, 0)::bigint::text as matched_amount_lamports,
  coalesce(lt.refunded_amount_lamports, 0)::bigint::text as refunded_amount_lamports,
  coalesce(lt.paid_amount_lamports, 0)::bigint::text as paid_amount_lamports,
  coalesce(pt.position_count, 0)::bigint as position_count,
  m.created_at,
  s.outcome,
  s.deciding_seq,
  s.evidence_seqs,
  s.tier,
  s.settled_at,
  p.status as proof_status,
  p.explorer_url,
  p.validate_stat_tx,
  p.merkle_proof,
  p.stat_key,
  p.seq as proof_seq
from markets m
join groups g on g.id = m.group_id
join claims c on c.id = m.claim_id
join memberships ms on ms.group_id = c.group_id and ms.user_id = c.claimer_user_id
left join position_totals pt on pt.market_id = m.id
left join ledger_totals lt on lt.market_id = m.id
left join lateral (
  select greatest(round(((1 - m.quote_probability) / m.quote_probability) * 1000)::bigint, 1) as ratio_milli
) ratio on true
left join lateral (
  select least(
    coalesce(pt.active_back_lamports, 0),
    (coalesce(pt.active_doubt_lamports, 0) * 1000) / ratio.ratio_milli
  ) as matched_back_lamports
) match_back on true
left join lateral (
  select
    match_back.matched_back_lamports,
    least(
    coalesce(pt.active_doubt_lamports, 0),
    (match_back.matched_back_lamports * ratio.ratio_milli) / 1000
    ) as matched_doubt_lamports
) match_totals on true
left join settlements s on s.market_id = m.id
left join lateral (
  select
    pr.status,
    pr.explorer_url,
    pr.validate_stat_tx,
    pr.merkle_proof,
    pr.stat_key,
    pr.seq
  from proofs pr
  where pr.market_id = m.id
  order by
    case pr.status
      when 'verified' then 4
      when 'pending' then 3
      when 'failed' then 2
      when 'unavailable' then 1
      else 0
    end desc,
    case pr.kind when 'stat' then 1 else 0 end desc,
    pr.id asc
  limit 1
) p on true
where g.web_enabled and m.currency = 'sol' and not m.is_replay;

create view public_group_board as
with position_totals as (
  select
    p.market_id,
    coalesce(sum(p.stake) filter (where p.side = 'back'), 0)::bigint as back_pot_lamports,
    coalesce(sum(p.stake) filter (where p.side = 'doubt'), 0)::bigint as doubt_pot_lamports,
    coalesce(sum(p.stake) filter (where p.side = 'back' and p.state = 'active'), 0)::bigint as active_back_lamports,
    coalesce(sum(p.stake) filter (where p.side = 'doubt' and p.state = 'active'), 0)::bigint as active_doubt_lamports,
    count(*)::bigint as position_count
  from positions p
  group by p.market_id
), ledger_totals as (
  select
    l.market_id,
    coalesce(sum(l.lamports) filter (where l.kind = 'refund' and l.lamports > 0), 0)::bigint as refunded_amount_lamports,
    coalesce(sum(l.lamports) filter (where l.kind = 'payout' and l.lamports > 0), 0)::bigint as paid_amount_lamports
  from wager_ledger_entries l
  where l.market_id is not null
  group by l.market_id
)
select
  m.id as market_id,
  g.slug as group_slug,
  m.spec,
  m.status,
  m.price_provenance,
  m.quote_probability,
  m.quote_multiplier,
  m.currency,
  coalesce(pt.back_pot_lamports, 0)::bigint::text as back_pot_lamports,
  coalesce(pt.doubt_pot_lamports, 0)::bigint::text as doubt_pot_lamports,
  coalesce(match_totals.matched_back_lamports + match_totals.matched_doubt_lamports, 0)::bigint::text as matched_amount_lamports,
  coalesce(lt.refunded_amount_lamports, 0)::bigint::text as refunded_amount_lamports,
  coalesce(lt.paid_amount_lamports, 0)::bigint::text as paid_amount_lamports,
  coalesce(pt.position_count, 0)::bigint as position_count,
  m.created_at,
  s.outcome,
  s.settled_at
from markets m
join groups g on g.id = m.group_id
left join position_totals pt on pt.market_id = m.id
left join ledger_totals lt on lt.market_id = m.id
left join lateral (
  select greatest(round(((1 - m.quote_probability) / m.quote_probability) * 1000)::bigint, 1) as ratio_milli
) ratio on true
left join lateral (
  select least(
    coalesce(pt.active_back_lamports, 0),
    (coalesce(pt.active_doubt_lamports, 0) * 1000) / ratio.ratio_milli
  ) as matched_back_lamports
) match_back on true
left join lateral (
  select
    match_back.matched_back_lamports,
    least(
    coalesce(pt.active_doubt_lamports, 0),
    (match_back.matched_back_lamports * ratio.ratio_milli) / 1000
    ) as matched_doubt_lamports
) match_totals on true
left join settlements s on s.market_id = m.id
where g.web_enabled and m.currency = 'sol' and not m.is_replay;

-- ── Public privileges and realtime invalidation only ───────────────────────

create function public_market_is_web_enabled(p_market_id uuid) returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from markets m
    join groups g on g.id = m.group_id
    where m.id = p_market_id
      and g.web_enabled
      and m.currency = 'sol'
      and not m.is_replay
  );
$$;

drop policy anon_read_settlements on settlements;
drop policy anon_read_proofs on proofs;
create policy public_realtime_settlements on settlements
  for select to anon, authenticated
  using (public_market_is_web_enabled(market_id));
create policy public_realtime_proofs on proofs
  for select to anon, authenticated
  using (public_market_is_web_enabled(market_id));

revoke all privileges on all tables in schema public from anon, authenticated;
grant select on public_receipts, public_group_board, public_evidence to anon, authenticated;
grant select on settlements, proofs to anon, authenticated;

revoke execute on function
  membership_public_alias_candidate(),
  membership_assign_public_alias(),
  onboarding_event_set_retention(),
  prune_onboarding_events(integer),
  public_market_is_web_enabled(uuid)
from public, anon, authenticated;
grant execute on function
  prune_onboarding_events(integer)
to service_role;
grant execute on function
  public_market_is_web_enabled(uuid)
to service_role, anon, authenticated;

alter publication supabase_realtime drop table markets;
