export const PUBLIC_RECEIPT_COLUMNS = [
  'back_pot_lamports',
  'created_at',
  'currency',
  'deciding_seq',
  'doubt_pot_lamports',
  'evidence_seqs',
  'explorer_url',
  'group_slug',
  'market_id',
  'matched_amount_lamports',
  'merkle_proof',
  'outcome',
  'paid_amount_lamports',
  'position_count',
  'price_provenance',
  'proof_seq',
  'proof_status',
  'quote_multiplier',
  'quote_probability',
  'refunded_amount_lamports',
  'settled_at',
  'spec',
  'stat_key',
  'status',
  'tier',
  'validate_stat_tx',
] as const;

export const PUBLIC_GROUP_BOARD_COLUMNS = [
  'back_pot_lamports',
  'created_at',
  'currency',
  'doubt_pot_lamports',
  'group_slug',
  'market_id',
  'matched_amount_lamports',
  'outcome',
  'paid_amount_lamports',
  'position_count',
  'price_provenance',
  'quote_multiplier',
  'quote_probability',
  'refunded_amount_lamports',
  'settled_at',
  'spec',
  'status',
] as const;

export const PRIVATE_PUBLIC_COLUMN = /(?:^|_)(?:alias|claimer|display_name|username|telegram_id|user_id|wallet|pubkey|quoted_text|position_id|participants?|side|result|points?|points_delta|wins|losses|accuracy|rank|current_streak|best_streak|leaderboard)(?:_|$)/i;
