export const TELEGRAM_TABLES = [
  'telegram_updates',
  'telegram_outbound_ownership_jobs',
  'engine_owned_messages',
  'engine_worker_heartbeats',
] as const;

export const TELEGRAM_FUNCTIONS = [
  'telegram_persist_update(text,text,bigint,text,jsonb,text)',
  'telegram_lease_updates(uuid,integer,integer)',
  'telegram_complete_update(uuid,uuid)',
  'telegram_retry_update(uuid,uuid,text,timestamp with time zone,integer)',
  'telegram_dead_letter_update(uuid,uuid,text)',
  'telegram_plan_outbound(text,bigint,text,text)',
  'telegram_start_outbound(uuid,uuid,integer)',
  'telegram_mark_outbound_owned(uuid,uuid,bigint)',
  'telegram_complete_outbound(uuid,uuid)',
  'telegram_mark_outbound_uncertain(uuid,uuid,text)',
  'telegram_sweep_expired_outbound(integer)',
  'telegram_lease_uncertain_ownership(uuid,integer,integer)',
  'telegram_lease_outbound_completion(uuid,integer,integer)',
  'telegram_reconcile_outbound(uuid,uuid,bigint)',
  'telegram_manual_review_outbound(uuid,uuid,text)',
  'telegram_resolve_owned_message(bigint,bigint)',
  'engine_heartbeat_worker(text,uuid,boolean)',
  'telegram_delivery_snapshot(timestamp with time zone)',
  'telegram_prune_delivery(integer)',
] as const;

export const TELEGRAM_FUNCTION_NAMES = [
  'telegram_persist_update',
  'telegram_lease_updates',
  'telegram_complete_update',
  'telegram_retry_update',
  'telegram_dead_letter_update',
  'telegram_plan_outbound',
  'telegram_start_outbound',
  'telegram_mark_outbound_owned',
  'telegram_complete_outbound',
  'telegram_mark_outbound_uncertain',
  'telegram_sweep_expired_outbound',
  'telegram_lease_uncertain_ownership',
  'telegram_lease_outbound_completion',
  'telegram_reconcile_outbound',
  'telegram_manual_review_outbound',
  'telegram_resolve_owned_message',
  'engine_heartbeat_worker',
  'telegram_delivery_snapshot',
  'telegram_prune_delivery',
] as const;
